[tool.poetry]
name = "sakstig"
version = "0.1.7"
description = ""
authors = []

[tool.poetry.dependencies]
python = "^3.7"
pyleri = "^1.3.2"

[tool.poetry.dev-dependencies]
nose = "^1.3.7"
ObjectPath = "^0.6.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
