name: Python application
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install pip/poetry
      run: |
        python -m pip install --upgrade pip
        pip install poetry
    - name: Set up app
      run: |
        poetry install
    - name: Clone ObjectPath
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
        repository: adriank/ObjectPath
        path: ObjectPath
    - name: Test
      run: |
        poetry run nosetests -v ./tests
